# .github/workflows/deploy.yml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
